import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

const AGENT_MODULE = 'sikulivs_debug.py';

export interface LauncherSpec {
    port: number;
    script: string;      // The .py file the user is debugging
    bundle: string;      // Folder SikuliX should resolve images against
    roots: string[];     // Folders whose files count as the user's own code
    stopOnEntry: boolean;
    captureDir: string;  // Where the agent writes screenshots
}

/**
 * The Jython file SikuliX is actually pointed at. It hands control to the agent, which
 * installs the tracer and then runs the user's script in this same namespace, so the
 * script sees the interpreter SikuliX prepared, header and all.
 */
export function launcherSource(spec: LauncherSpec, agentDir: string): string {
    return [
        '# -*- coding: utf-8 -*-',
        '# Generated by SikuliVS. Runs a script under the debug agent.',
        'import sys',
        `sys.path.insert(0, ${literal(agentDir)})`,
        'import sikulivs_debug',
        'sikulivs_debug.launch(',
        `    ${spec.port},`,
        `    ${literal(spec.script)},`,
        `    ${literal(spec.bundle)},`,
        `    [${spec.roots.map(literal).join(', ')}],`,
        `    ${spec.stopOnEntry ? 'True' : 'False'},`,
        `    ${literal(spec.captureDir)},`,
        '    globals())',
        ''
    ].join('\n');
}

/**
 * A Python unicode literal. JSON's escaping is a subset of Python's, and the `u` prefix
 * makes `\uXXXX` mean the same thing in Jython 2 that it does in the JSON it came from.
 */
function literal(value: string): string {
    return `u${JSON.stringify(value)}`;
}

/**
 * Lays down the launcher and a copy of the agent in a private directory.
 *
 * The agent is copied rather than imported from the extension folder because Jython
 * writes a compiled `$py.class` beside whatever it imports, and an installed extension
 * is not somewhere to be writing files.
 */
export function writeLaunchDir(spec: LauncherSpec, extensionPath: string): string {
    // Not "sikulivs-": SikuliX clears temp directories whose names begin with
    // "sikuli" when it exits. See the note in captures.ts.
    const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'svs-launch-'));

    fs.copyFileSync(
        path.join(extensionPath, 'pysrc', AGENT_MODULE),
        path.join(directory, AGENT_MODULE)
    );
    const launcher = path.join(directory, 'sikulivs_launch.py');
    fs.writeFileSync(launcher, launcherSource(spec, directory), 'utf8');

    return launcher;
}

export function removeLaunchDir(launcher: string): void {
    try {
        fs.rmSync(path.dirname(launcher), { recursive: true, force: true });
    } catch {
        // A leftover temp folder is not worth failing a session over.
    }
}

/**
 * Where a breakpoint on `line` can actually be hit.
 *
 * Jython only reports line events for lines that carry code, so a breakpoint on a blank
 * line or a comment would silently never fire. Moving it to the next line that has
 * something on it matches what other debuggers do and keeps the marker honest.
 */
export function executableLine(source: string[], line: number): number {
    for (let candidate = line; candidate <= source.length; candidate++) {
        const text = (source[candidate - 1] ?? '').trim();
        if (text !== '' && !text.startsWith('#')) {
            return candidate;
        }
    }
    return line;
}
